Restructure Code
zrottman/dns_c pull request #50
Opened 2023-10-31 21:42 UTC by zrottman

Curious for feedback as to how I've clustered functionality thus far before proceeding further. Does this seem like a reasonable way to organize the code?

2023-11-04 18:34 UTC, pjg11 requested changes
I've suggested two changes, everything else looks good to me

2023-11-04 18:34 UTC, pjg11 commented on src/dns.c
> +
Re-add `<stdlib.h>` as running the code without it returned errors.

2023-11-04 18:34 UTC, pjg11 commented on src/dns.h
> +static void         display_DNSRecord(DNSRecord *record);
From a structure point of view, Packet = Header + Questions + Records, so the DNS Packet functions could be placed after DNS Record

2023-11-07 16:45 UTC, zrottman commented
As discussed, noting here that, to avoid a painful merge with recent changes to `main`, we should abandon this branch and create a new branch from `main` for this issue.

2023-11-14 19:59 UTC, zrottman commented
Replaced by #55

2023-11-14 19:59 UTC, closed without merging